### ISSUE TITLE
web3j version in starter is outdated

### ISSUE THREAD

**Issue by javahippie** [web3j/web3j-spring-boot-starter#17]
The latest version of this spring boot starter links to web3j version 3.3.1, which is quite old. If I install the command line tools on my mac via `brew install`, the code generator in the command line client is not compatible with the web3j version in the spring boot starter. Is this something that could be updated?

**Comment by jknap** [comment]
Any news on this issue?

**Comment by iikirilov** [comment]
using web3j 4.0.3
