### ISSUE TITLE
org.web3j.protocol.core.filters.FilterException: Invalid request: filter not found

### ISSUE THREAD

**Issue by 401825317** [web3j/web3j-spring-boot-starter#19]
![image](https://user-images.githubusercontent.com/19526136/47764211-26c4c100-dcff-11e8-8c60-e9fe13523bb3.png)

@ligi @psylinse @jorpic @matthewleon my block server is OK
can you help me ?thanks

**Comment by ganchix** [comment]
Can you put your filter code? I believe you have to put this issue in the library web3j not in the integration with Spring Boot, because this is the filter request.

**Comment by 401825317** [comment]
@ganchix 
@SuppressWarnings("unused")
	public void catchUpFilter(long number) {
		log.debug("catchUpFilter start block.........................");
		BigInteger startBlock = BigInteger.ZERO;

		if (redisLock.checkKey(ParamConsts.REDIS_START_BLOCK_NUMBER)) {
			startBlock = new BigInteger(redisLock.getStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER));
			// startBlock=redisManager.string_set(consts.getREDIS_SCHEME_PRODUCT(),
			// ParamConsts.REDIS_START_BLOCK_NUMBER, value);
		} else {
			startBlock = BigInteger.valueOf(number);
		}
		/**
		 * 遍历旧区块，监听新区块
		 */

		EthFilter filter = new EthFilter(DefaultBlockParameter.valueOf(startBlock), DefaultBlockParameterName.LATEST,
		// "0xed0588ae6ad1e5abd1957cc77f4aded77ab425ae");
						consts.getECOMCONTRACTADDRESS());
		Event event = new Event("Transfer", Arrays.<TypeReference<?>> asList(new TypeReference<Address>() {
		}, new TypeReference<Address>() {
		}), Arrays.<TypeReference<?>> asList(new TypeReference<Uint256>() {
		}));

		String topicData = EventEncoder.encode(event);
		filter.addSingleTopic(topicData);
		log.debug("start block.........................:{}",startBlock);
		try {
			web3j.ethLogObservable(filter).subscribe(eventlog -> {
				String eventlogstr = JSON.toJSONString(eventlog);
				log.debug("Transfer log:{}", eventlogstr);
				List<org.web3j.abi.datatypes.Type> results = FunctionReturnDecoder.decode(eventlog.getData(), event.getNonIndexedParameters());
				RechargeModel model = new RechargeModel();
				List<String> topics = eventlog.getTopics();
				Event address = new Event("Transfer", Arrays.<TypeReference<?>> asList(new TypeReference<Address>() {
				}), Arrays.<TypeReference<?>> asList(new TypeReference<Uint256>() {
				}));
				String from = FunctionReturnDecoder.decode(topics.get(1), address.getIndexedParameters()).get(0).getValue().toString();
				String to = FunctionReturnDecoder.decode(topics.get(2), address.getIndexedParameters()).get(0).getValue().toString();
				WalletTokenModel walletTokenModel = new WalletTokenModel();
				walletTokenModel.setAddr(to);
				int tokenid = tokenMapper.getModelForName(ParamConsts.PARAM_ECOM).getTid();
				walletTokenModel.setTokenid(tokenid);
				walletTokenModel = walletTokenMapper.getModelForAddr(walletTokenModel);
				log.debug("address:{},查询到的walletTokenModel:{}",to,JSON.toJSONString(walletTokenModel));
				BigInteger firstBlockNumber = eventlog.getBlockNumber();
				if (walletTokenModel != null) {
					model = rechargeMapper.getModelForTranscationhash(eventlog.getTransactionHash());
					if (model == null) {
						model = new RechargeModel();
						model.setReceivables(to);
						model.setTransactionhash(eventlog.getTransactionHash());
						model.setReceivablesuserid(walletTokenModel.getUserid());
						model.setPayer(from);
						BigInteger nowBlockNumber;
						BigInteger confirmblock;
						try {
							BigInteger value = (BigInteger) results.get(0).getValue();
							value = value.divide(ParamConsts.PARAM_ECOM_SCALE);
							nowBlockNumber = web3j.ethBlockNumber().send().getBlockNumber();
							confirmblock = nowBlockNumber.subtract(firstBlockNumber);
							model.setFirstblocknumber(firstBlockNumber);
							model.setConfirmblock(confirmblock);
							model.setFinishblock(BigInteger.valueOf(12));
							if (confirmblock.compareTo(model.getFinishblock()) > 0) {
								model.setState(0);
								walletTokenModel = walletTokenMapper.getModelForAddrLock(walletTokenModel);
								walletTokenModel.setAvailablemoney(walletTokenModel.getAvailablemoney().add(BigDecimal.valueOf(value.longValue())));
								walletTokenModel.setMoney(walletTokenModel.getAvailablemoney().add(walletTokenModel.getUnavailablemoney()));
							} else {
								model.setState(2);
							}
							model.setCreatetime(System.currentTimeMillis());
							model.setMoney(BigDecimal.valueOf(value.longValue()));
							model.setTokenid(tokenid);
//							walletTokenModel.setAvailablemoney(walletTokenModel.getAvailablemoney().add((BigDecimal.valueOf(value.longValue()))));
//							walletTokenModel.setMoney(walletTokenModel.getAvailablemoney().add(walletTokenModel.getUnavailablemoney()));
							WalletTokenModel tokenModel = new WalletTokenModel();
							WalletLogModel logModel = new WalletLogModel();
							logModel.setCreatetime(System.currentTimeMillis());
							logModel.setLogtype(WalletLogType.RECHARGE.ordinal());
							logModel.setMoney(BigDecimal.valueOf(value.longValue()));
							logModel.setPayer(from);
							logModel.setReceivables(to);
							logModel.setReceivablesuserid(walletTokenModel.getUserid());
							logModel.setRecharge(model);
							logModel.setUserid(walletTokenModel.getUserid());
							logModel.setWalletflownumber(idutils.getPayFlowNumberNextId(String.valueOf(tokenid)));
							logModel.setTokenid(tokenid);
							walletTokenService.insertRecharge(walletTokenModel,model,logModel);
							log.debug("address:{},充值{}ECOM成功",to,value);
						} catch (Exception e) {
							log.error("block insert ecom error:{}", ExceptionUtils.getStackTrace(e));
						}
					}else{
						log.debug("交易流水号已存在:{},检测块儿确认状态",eventlog.getTransactionHash());
//						if(model.getConfirmblock().compareTo(model.getFinishblock())<0) {
							Map<String, String> map = Maps.newHashMap();
							map.put("tasktype", ParamConsts.PARAM_TASK_WALLET_UPDATEBLOCK);
							map.put("tokenid", String.valueOf(model.getTokenid()));
							map.put("firstblocknumber", firstBlockNumber.toString());
							map.put("userid", walletTokenModel.getUserid());
							map.put("rid", String.valueOf(model.getRid()));
							walletTokenService.submit(map);
//						}
					}
				}
				String newRedisBlockValue = redisLock.getStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER);
				BigInteger newRedisBlock = BigInteger.ZERO;
				if (StringUtils.isNotBlank(newRedisBlockValue)) {
					newRedisBlock = new BigInteger(newRedisBlockValue);
					if (newRedisBlock.compareTo(firstBlockNumber) < 0) {
						log.debug("检测到新块儿高度....." + firstBlockNumber.toString());
						redisLock.setStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER, firstBlockNumber.toString());
					}else{
						log.debug("检测到块儿高度....." + firstBlockNumber.toString());
					}
				} else {
					log.debug("未检测到redis块儿高度....." + firstBlockNumber.toString());
					redisLock.setStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER, firstBlockNumber.toString());
				}
			});
		} catch (Exception e) {
			log.error("监听error:{}",ExceptionUtils.getStackTrace(e));
			log.error("监听error:{}",ExceptionUtils.getStackTrace(e));
			log.error("监听error:{}",ExceptionUtils.getStackTrace(e));
			log.error("监听error:{}",ExceptionUtils.getStackTrace(e));
			log.error("监听error:{}",ExceptionUtils.getStackTrace(e));
		}
try {
			/**
			 * 遍历旧交易，监听新交易
			 */
			@SuppressWarnings("rawtypes")
			Subscription subscription2 = web3j.catchUpToLatestAndSubscribeToNewTransactionsObservable(DefaultBlockParameter.valueOf(startBlock)).subscribe(res -> {
				Transaction tx = res;
				log.debug("tx" + JSON.toJSONString(res));
				if (StringUtils.isNotBlank(tx.getTo()) && tx.getValue().longValue() != 0) {
					RechargeModel model = new RechargeModel();
					Event address = new Event("Transfer", Arrays.<TypeReference<?>> asList(new TypeReference<Address>() {
					}), Arrays.<TypeReference<?>> asList(new TypeReference<Uint256>() {
					}));
					String to = FunctionReturnDecoder.decode(tx.getTo(), address.getIndexedParameters()).get(0).getValue().toString();
					String from = FunctionReturnDecoder.decode(tx.getFrom(), address.getIndexedParameters()).get(0).getValue().toString();
					WalletTokenModel walletTokenModel = new WalletTokenModel();
					walletTokenModel.setAddr(to);
					int tokenid = tokenMapper.getModelForName(ParamConsts.PARAM_ETH).getTid();
					walletTokenModel.setTokenid(tokenid);
					walletTokenModel = walletTokenMapper.getModelForAddr(walletTokenModel);
					BigInteger firstBlockNumber = tx.getBlockNumber();
					if (walletTokenModel != null) {
//						Object savePoint = TransactionAspectSupport.currentTransactionStatus().createSavepoint();
						model = rechargeMapper.getModelForTranscationhash(tx.getHash());
						if (model == null) {
							model = new RechargeModel();
							model.setReceivables(to);
							model.setTransactionhash(tx.getHash());
							model.setReceivablesuserid(walletTokenModel.getUserid());
							model.setPayer(from);
							BigInteger nowBlockNumber;
							BigInteger confirmblock;
							try {
								nowBlockNumber = web3j.ethBlockNumber().send().getBlockNumber();
								confirmblock = nowBlockNumber.subtract(firstBlockNumber);
								model.setConfirmblock(confirmblock);
								model.setFinishblock(BigInteger.valueOf(12));
								if (confirmblock.compareTo(model.getFinishblock()) > 0) {
									model.setState(0);
								} else {
									model.setState(2);
								}
								model.setCreatetime(System.currentTimeMillis());
								BigInteger value = (BigInteger) tx.getValue().divide(ParamConsts.PARAM_ECOM_SCALE);
								model.setMoney(BigDecimal.valueOf(value.longValue()));
								model.setTokenid(tokenid);
								rechargeMapper.insert(model);
								WalletLogModel logModel = new WalletLogModel();
								logModel.setCreatetime(System.currentTimeMillis());
								logModel.setLogtype(WalletLogType.RECHARGE.ordinal());
								logModel.setMoney(BigDecimal.valueOf(value.longValue()));
								logModel.setPayer(from);
								logModel.setReceivables(to);
								logModel.setReceivablesuserid(walletTokenModel.getUserid());
								logModel.setRecharge(model);
								logModel.setUserid(walletTokenModel.getUserid());
								logModel.setWalletflownumber(idutils.getPayFlowNumberNextId(String.valueOf(tokenid)));
								logModel.setTokenid(tokenid);
								walletLogMapper.insert(logModel);
								Map<String, String> map = Maps.newHashMap();
								map.put("tasktype", ParamConsts.PARAM_TASK_WALLET_UPDATEBLOCK);
								map.put("tokenid", String.valueOf(tokenid));
								map.put("firstblocknumber", String.valueOf(firstBlockNumber));
								map.put("userid", walletTokenModel.getUserid());
								map.put("rid", String.valueOf(model.getRid()));
								walletTokenService.submit(map);
							} catch (Exception e) {
								log.error("block insert eth error:{}", ExceptionUtils.getStackTrace(e));
//								TransactionAspectSupport.currentTransactionStatus().rollbackToSavepoint(savePoint);
							} finally {
								String newRedisBlockValue = redisLock.getStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER);
								BigInteger newRedisBlock = BigInteger.ZERO;
								if (StringUtils.isNotBlank(newRedisBlockValue)) {
									newRedisBlock = new BigInteger(newRedisBlockValue);
									if (newRedisBlock.compareTo(firstBlockNumber) < 0) {
										redisLock.setStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER, firstBlockNumber.toString());
									}
								} else {
									redisLock.setStringValue(ParamConsts.REDIS_START_BLOCK_NUMBER, firstBlockNumber.toString());
								}
							}
						}

					}
				}
			});
		} catch (Exception e) {
			log.error("监听error:{}",ExceptionUtils.getStackTrace(e));
		}
	}

**Comment by ganchix** [comment]
Please review the documentation for filter contract https://docs.web3j.io/filters.html#topic-filters-and-evm-events .

Are you using infura for this?

**Comment by 401825317** [comment]
No, we are our own block chain servers.

**Comment by 401825317** [comment]
我重新启动了区块服务器和APP服务器，这个问题解决了，但是我发现现在只接收一遍日志之后就接收不到日志订阅了

I restarted the Block Server and the APP Server, which solved the problem, but now I find that I can't receive log subscriptions after only receiving the log once.

**Comment by iikirilov** [comment]
This issue is fixed in web3j - if you have other problems please open a new issue
