### ISSUE TITLE
Hi, would this adapt to spring boot 2.0?

### ISSUE THREAD

**Issue by LycrusHamster** [web3j/web3j-spring-boot-starter#8]
Hi, since spring boot 2.0 is release. Would you please adapt this project to latest spring boot?

**Comment by conor10** [comment]
I'm certainly keen to see this. A community pull request with this functionality would be much appreciated.

**Comment by SnuK87** [comment]
@conor10 There are some open PRs. Would be nice to see one of them merged or see some feedback if there is a reason that none of those was merged yet.

**Comment by iikirilov** [comment]
using spring-boot 2.0.6
